// ============================================================
// 舌象案例库 · 本地内置包（小程序端运行时使用，不走云系统）
// ------------------------------------------------------------
// 本文件由 src/scripts/gen_tongue_cases_local.ts 生成，请勿手改。
// 20 条去标识案例，全部由真实引擎（tongue-engine-v2 + tongue-report）派生，
// 与云端 tongue_cases 表同源、与 App 展示同源，避免算法漂移。
// 小程序「数据库参考 / 食养画像」直接读此处，完全离线、零跨境请求。
// ============================================================
import type { TongueCaseRow } from '@/db/tongue-cases'

export const LOCAL_TONGUE_CASES: TongueCaseRow[] = [
  {
    case_no: 'TC-0001',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"淡红 / 粉红（常见）","coat_color":"薄白苔（常见）","coat_texture":"薄而均匀（常见）","teeth":"没有明显齿痕（常见）","crack":"没有明显裂纹（常见）","moist":"润泽（常见）","sublingual":"淡红、细而短（常见）"},
    answers: [0, 0, 0, 0, 0, 0, 0, 0],
    constitution_primary: 'pinghe',
    constitution_secondary: null,
    health_index: 96.0,
    band: 'low',
    confidence: 0.95,
    tags: ['平和', '舌淡红', '苔薄白'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0002',
    source: 'expert',
    features: {"area":"胖大（伸舌抵齿）","color":"偏淡白（颜色发浅）","coat_color":"薄白苔（常见）","coat_texture":"水滑多津","teeth":"明显齿痕（胖大舌）","crack":"没有明显裂纹（常见）","moist":"滑腻多津","sublingual":"淡红、细而短（常见）"},
    answers: [1, 1, 0, 4, 2, 0, 2, 0],
    constitution_primary: 'yangxu',
    constitution_secondary: 'tanshi',
    health_index: 47.8,
    band: 'high',
    confidence: 0.74,
    tags: ['阳虚', '舌淡白', '胖大舌', '苔水滑'],
    expert_note: '典型阳虚舌：淡白胖大、苔水滑',
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0003',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"偏淡白（颜色发浅）","coat_color":"薄白苔（常见）","coat_texture":"薄而均匀（常见）","teeth":"轻度齿痕","crack":"没有明显裂纹（常见）","moist":"润泽（常见）","sublingual":"淡红、细而短（常见）"},
    answers: [0, 1, 0, 0, 1, 0, 0, 0],
    constitution_primary: 'yangxu',
    constitution_secondary: null,
    health_index: 86.4,
    band: 'low',
    confidence: 0.61,
    tags: ['阳虚', '舌淡白'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0004',
    source: 'expert',
    features: {"area":"正常大小（常见）","color":"偏红（比常人红）","coat_color":"少苔 / 无苔（舌面光红）","coat_texture":"少而干","teeth":"没有明显齿痕（常见）","crack":"有裂纹 / 裂沟","moist":"偏干 / 少津","sublingual":"淡红、细而短（常见）"},
    answers: [0, 2, 4, 3, 0, 1, 1, 0],
    constitution_primary: 'yinxu',
    constitution_secondary: null,
    health_index: 48.0,
    band: 'high',
    confidence: 0.85,
    tags: ['阴虚', '舌红', '少苔', '裂纹'],
    expert_note: '典型阴虚舌：舌红少苔、有裂纹',
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0005',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"偏红（比常人红）","coat_color":"淡黄苔","coat_texture":"厚而干","teeth":"没有明显齿痕（常见）","crack":"有裂纹 / 裂沟","moist":"偏干 / 少津","sublingual":"淡红、细而短（常见）"},
    answers: [0, 2, 2, 2, 0, 1, 1, 0],
    constitution_primary: 'yinxu',
    constitution_secondary: 'shire',
    health_index: 51.0,
    band: 'high',
    confidence: 0.78,
    tags: ['阴虚', '舌红', '苔干'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0006',
    source: 'engine',
    features: {"area":"胖大（伸舌抵齿）","color":"淡红 / 粉红（常见）","coat_color":"薄白苔（常见）","coat_texture":"薄而均匀（常见）","teeth":"轻度齿痕","crack":"没有明显裂纹（常见）","moist":"润泽（常见）","sublingual":"淡红、细而短（常见）"},
    answers: [1, 0, 0, 0, 1, 0, 0, 0],
    constitution_primary: 'qixu',
    constitution_secondary: null,
    health_index: 76.8,
    band: 'mid',
    confidence: 0.69,
    tags: ['气虚', '胖大舌', '齿痕'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0007',
    source: 'engine',
    features: {"area":"胖大（伸舌抵齿）","color":"偏淡白（颜色发浅）","coat_color":"白而厚","coat_texture":"厚腻","teeth":"明显齿痕（胖大舌）","crack":"没有明显裂纹（常见）","moist":"滑腻多津","sublingual":"淡红、细而短（常见）"},
    answers: [1, 1, 1, 1, 2, 0, 2, 0],
    constitution_primary: 'tanshi',
    constitution_secondary: 'qixu',
    health_index: 35.0,
    band: 'high',
    confidence: 0.95,
    tags: ['气虚', '痰湿', '胖大舌', '苔厚腻'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0008',
    source: 'expert',
    features: {"area":"正常大小（常见）","color":"淡红 / 粉红（常见）","coat_color":"白而厚","coat_texture":"厚腻","teeth":"明显齿痕（胖大舌）","crack":"没有明显裂纹（常见）","moist":"滑腻多津","sublingual":"淡红、细而短（常见）"},
    answers: [0, 0, 1, 1, 2, 0, 2, 0],
    constitution_primary: 'tanshi',
    constitution_secondary: null,
    health_index: 64.0,
    band: 'high',
    confidence: 0.80,
    tags: ['痰湿', '苔白厚腻', '齿痕', '苔滑'],
    expert_note: '典型痰湿舌：苔白厚腻、边有齿痕',
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0009',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"偏红（比常人红）","coat_color":"黄厚腻苔","coat_texture":"厚腻","teeth":"轻度齿痕","crack":"没有明显裂纹（常见）","moist":"偏干 / 少津","sublingual":"淡红、细而短（常见）"},
    answers: [0, 2, 3, 1, 1, 0, 1, 0],
    constitution_primary: 'shire',
    constitution_secondary: 'tanshi',
    health_index: 57.8,
    band: 'high',
    confidence: 0.80,
    tags: ['湿热', '舌红', '苔黄厚腻'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0010',
    source: 'expert',
    features: {"area":"正常大小（常见）","color":"暗红 / 绛红","coat_color":"黄厚腻苔","coat_texture":"厚腻","teeth":"轻度齿痕","crack":"没有明显裂纹（常见）","moist":"偏干 / 少津","sublingual":"青紫明显 / 曲张如小鱼"},
    answers: [0, 3, 3, 1, 1, 0, 1, 2],
    constitution_primary: 'shire',
    constitution_secondary: 'tanshi',
    health_index: 57.8,
    band: 'high',
    confidence: 0.79,
    tags: ['湿热', '血瘀', '舌暗红', '苔黄厚腻', '舌下络脉曲张'],
    expert_note: '湿热挟瘀：舌暗红、苔黄厚腻、舌下络脉曲张',
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0011',
    source: 'expert',
    features: {"area":"正常大小（常见）","color":"青紫 / 暗紫","coat_color":"薄白苔（常见）","coat_texture":"薄而均匀（常见）","teeth":"没有明显齿痕（常见）","crack":"没有明显裂纹（常见）","moist":"润泽（常见）","sublingual":"青紫明显 / 曲张如小鱼"},
    answers: [0, 4, 0, 0, 0, 0, 0, 2],
    constitution_primary: 'xueyu',
    constitution_secondary: null,
    health_index: 70.4,
    band: 'mid',
    confidence: 0.70,
    tags: ['血瘀', '舌青紫', '舌下络脉曲张'],
    expert_note: '典型血瘀舌：舌青紫、舌下络脉青紫曲张',
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0012',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"暗红 / 绛红","coat_color":"薄白苔（常见）","coat_texture":"薄而均匀（常见）","teeth":"没有明显齿痕（常见）","crack":"没有明显裂纹（常见）","moist":"润泽（常见）","sublingual":"偏青紫、略粗"},
    answers: [0, 3, 0, 0, 0, 0, 0, 1],
    constitution_primary: 'xueyu',
    constitution_secondary: null,
    health_index: 83.2,
    band: 'mid',
    confidence: 0.66,
    tags: ['血瘀', '舌暗红', '舌下络脉偏粗'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0013',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"偏红（比常人红）","coat_color":"黄厚腻苔","coat_texture":"厚腻","teeth":"轻度齿痕","crack":"没有明显裂纹（常见）","moist":"偏干 / 少津","sublingual":"偏青紫、略粗"},
    answers: [0, 2, 3, 1, 1, 0, 1, 1],
    constitution_primary: 'shire',
    constitution_secondary: 'tanshi',
    health_index: 57.8,
    band: 'high',
    confidence: 0.86,
    tags: ['湿热', '苔黄厚腻'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0014',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"暗红 / 绛红","coat_color":"少苔 / 无苔（舌面光红）","coat_texture":"少而干","teeth":"没有明显齿痕（常见）","crack":"有裂纹 / 裂沟","moist":"偏干 / 少津","sublingual":"偏青紫、略粗"},
    answers: [0, 3, 4, 3, 0, 1, 1, 1],
    constitution_primary: 'yinxu',
    constitution_secondary: null,
    health_index: 54.4,
    band: 'high',
    confidence: 0.95,
    tags: ['阴虚', '血瘀', '舌暗红', '少苔', '裂纹'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0015',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"偏淡白（颜色发浅）","coat_color":"薄白苔（常见）","coat_texture":"水滑多津","teeth":"没有明显齿痕（常见）","crack":"没有明显裂纹（常见）","moist":"滑腻多津","sublingual":"淡红、细而短（常见）"},
    answers: [0, 1, 0, 4, 0, 0, 2, 0],
    constitution_primary: 'yangxu',
    constitution_secondary: null,
    health_index: 70.4,
    band: 'mid',
    confidence: 0.79,
    tags: ['阳虚', '舌淡白', '苔水滑'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0016',
    source: 'engine',
    features: {"area":"胖大（伸舌抵齿）","color":"淡红 / 粉红（常见）","coat_color":"薄白苔（常见）","coat_texture":"薄而均匀（常见）","teeth":"轻度齿痕","crack":"没有明显裂纹（常见）","moist":"偏干 / 少津","sublingual":"淡红、细而短（常见）"},
    answers: [1, 0, 0, 0, 1, 0, 1, 0],
    constitution_primary: 'qixu',
    constitution_secondary: null,
    health_index: 76.8,
    band: 'mid',
    confidence: 0.74,
    tags: ['气虚', '胖大舌', '齿痕'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0017',
    source: 'engine',
    features: {"area":"胖大（伸舌抵齿）","color":"淡红 / 粉红（常见）","coat_color":"白而厚","coat_texture":"厚腻","teeth":"明显齿痕（胖大舌）","crack":"没有明显裂纹（常见）","moist":"滑腻多津","sublingual":"淡红、细而短（常见）"},
    answers: [1, 0, 1, 1, 2, 0, 2, 0],
    constitution_primary: 'tanshi',
    constitution_secondary: null,
    health_index: 51.2,
    band: 'high',
    confidence: 0.93,
    tags: ['痰湿', '胖大舌', '苔厚腻', '齿痕'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0018',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"偏红（比常人红）","coat_color":"淡黄苔","coat_texture":"薄而均匀（常见）","teeth":"没有明显齿痕（常见）","crack":"没有明显裂纹（常见）","moist":"润泽（常见）","sublingual":"淡红、细而短（常见）"},
    answers: [0, 2, 2, 0, 0, 0, 0, 0],
    constitution_primary: 'shire',
    constitution_secondary: null,
    health_index: 80.0,
    band: 'mid',
    confidence: 0.66,
    tags: ['湿热', '舌红', '苔淡黄'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0019',
    source: 'engine',
    features: {"area":"胖大（伸舌抵齿）","color":"暗红 / 绛红","coat_color":"白而厚","coat_texture":"厚腻","teeth":"明显齿痕（胖大舌）","crack":"没有明显裂纹（常见）","moist":"滑腻多津","sublingual":"青紫明显 / 曲张如小鱼"},
    answers: [1, 3, 1, 1, 2, 0, 2, 2],
    constitution_primary: 'tanshi',
    constitution_secondary: null,
    health_index: 51.2,
    band: 'high',
    confidence: 0.95,
    tags: ['血瘀', '痰湿', '舌暗红', '苔厚腻', '舌下络脉曲张'],
    expert_note: null,
    created_at: '2026-10-03',
  },
  {
    case_no: 'TC-0020',
    source: 'engine',
    features: {"area":"正常大小（常见）","color":"偏淡白（颜色发浅）","coat_color":"薄白苔（常见）","coat_texture":"薄而均匀（常见）","teeth":"没有明显齿痕（常见）","crack":"没有明显裂纹（常见）","moist":"偏干 / 少津","sublingual":"淡红、细而短（常见）"},
    answers: [0, 1, 0, 0, 0, 0, 1, 0],
    constitution_primary: 'yangxu',
    constitution_secondary: null,
    health_index: 86.4,
    band: 'low',
    confidence: 0.61,
    tags: ['阳虚', '舌淡白'],
    expert_note: null,
    created_at: '2026-10-03',
  },
]
