-- 补齐「线上已存在、但从未纳入迁移管理」的 3 张表（schema drift）
--
-- 背景：这三张表由早期手工建库产生，216 个迁移里找不到任何建表语句。
-- 线上探测（anon key 直读）确认均存在且有数据：
--   cities      城市字典，小程序「城市选择 / 定位」在用（缺失会导致换环境直接不可用）
--   home_ads    首页广告位（旧版，后台现改走 site_configs.home_ad_slots）
--   trigger_logs 触发器/打印等动作日志，由 Edge Function 写入
--
-- 全部使用 CREATE TABLE IF NOT EXISTS：线上已存在则整段跳过，不会改动任何现有数据或权限。
-- 刻意不写 ENABLE ROW LEVEL SECURITY / policy：线上这三张表的 RLS 状态未在迁移中记录，
-- 贸然 ENABLE 而无配套 policy 会直接锁死小程序的匿名读取。RLS 状态维持现状。

-- 城市字典：小程序城市选择、定位匹配
CREATE TABLE IF NOT EXISTS public.cities (
  id         integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_code  text,
  city_name  text,
  province   text,
  lng        double precision,
  lat        double precision,
  status     text         DEFAULT 'active',
  pinyin     text,
  initial    text,
  is_hot     boolean      DEFAULT false,
  sort_order integer      DEFAULT 0,
  created_at timestamptz  DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cities_status ON public.cities (status);
CREATE INDEX IF NOT EXISTS idx_cities_name ON public.cities (city_name);

COMMENT ON TABLE public.cities IS '城市字典（schema drift 补录，原手工建库）';

-- 首页广告位（旧版）。新版后台改用 site_configs.home_ad_slots，此表保留供历史数据查询
CREATE TABLE IF NOT EXISTS public.home_ads (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  media_type text   DEFAULT 'image',
  media_url  text,
  poster_url text,
  link_url   text,
  title      text,
  sort_order integer DEFAULT 0,
  is_active  boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_home_ads_active ON public.home_ads (is_active, sort_order);

COMMENT ON TABLE public.home_ads IS '首页广告位旧版（schema drift 补录）；新版读 site_configs.home_ad_slots';

-- 动作日志：打印触发器、分佣重试等 EF 写入的执行记录
CREATE TABLE IF NOT EXISTS public.trigger_logs (
  id         integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no   text,
  action     text,
  error      text,
  created_at timestamptz  DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trigger_logs_order ON public.trigger_logs (order_no);
CREATE INDEX IF NOT EXISTS idx_trigger_logs_created ON public.trigger_logs (created_at DESC);

COMMENT ON TABLE public.trigger_logs IS 'EF 动作日志（schema drift 补录），如 PRINT_ENTER / 分佣失败等';
